apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/guilhem/token-renewer/config/default?ref=main

patches:
  - path: plugin-container-patch.yaml
    target:
      kind: Deployment
      labelSelector: control-plane=controller-manager,app.kubernetes.io/name=token-renewer
