apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
spec:
  template:
    spec:
      containers:
        - name: linode-plugin
          image: linode-plugin
          command:
            - /linode-plugin
          volumeMounts:
            - name: plugins
              mountPath: "/plugins"
