# This rule is not used by the project token-renewer itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over token-renewer.barpilot.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: token-renewer
    app.kubernetes.io/managed-by: kustomize
  name: token-admin-role
rules:
- apiGroups:
  - token-renewer.barpilot.io
  resources:
  - tokens
  verbs:
  - '*'
- apiGroups:
  - token-renewer.barpilot.io
  resources:
  - tokens/status
  verbs:
  - get
