apiVersion: token-renewer.barpilot.io/v1beta1
kind: Token
metadata:
  labels:
    app.kubernetes.io/name: token-renewer
    app.kubernetes.io/managed-by: kustomize
  name: token-sample
spec:
  # TODO(user): Add fields here
