// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: barpilot/token_renewer/v1/token.proto

package shared

import (
	v1 "github.com/guilhem/operator-plugin-framework/pluginframework/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RenewTokenRequest is the request message for the RenewToken RPC.
type RenewTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      string                 `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewTokenRequest) Reset() {
	*x = RenewTokenRequest{}
	mi := &file_barpilot_token_renewer_v1_token_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewTokenRequest) ProtoMessage() {}

func (x *RenewTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_barpilot_token_renewer_v1_token_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewTokenRequest.ProtoReflect.Descriptor instead.
func (*RenewTokenRequest) Descriptor() ([]byte, []int) {
	return file_barpilot_token_renewer_v1_token_proto_rawDescGZIP(), []int{0}
}

func (x *RenewTokenRequest) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *RenewTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// RenewTokenResponse is the response message for the RenewToken RPC.
type RenewTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	NewMetadata   string                 `protobuf:"bytes,2,opt,name=new_metadata,json=newMetadata,proto3" json:"new_metadata,omitempty"`
	Expiration    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expiration,proto3" json:"expiration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewTokenResponse) Reset() {
	*x = RenewTokenResponse{}
	mi := &file_barpilot_token_renewer_v1_token_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewTokenResponse) ProtoMessage() {}

func (x *RenewTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_barpilot_token_renewer_v1_token_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewTokenResponse.ProtoReflect.Descriptor instead.
func (*RenewTokenResponse) Descriptor() ([]byte, []int) {
	return file_barpilot_token_renewer_v1_token_proto_rawDescGZIP(), []int{1}
}

func (x *RenewTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RenewTokenResponse) GetNewMetadata() string {
	if x != nil {
		return x.NewMetadata
	}
	return ""
}

func (x *RenewTokenResponse) GetExpiration() *timestamppb.Timestamp {
	if x != nil {
		return x.Expiration
	}
	return nil
}

// GetTokenValidityRequest is the request message for the GetTokenValidity RPC.
type GetTokenValidityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      string                 `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTokenValidityRequest) Reset() {
	*x = GetTokenValidityRequest{}
	mi := &file_barpilot_token_renewer_v1_token_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokenValidityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenValidityRequest) ProtoMessage() {}

func (x *GetTokenValidityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_barpilot_token_renewer_v1_token_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenValidityRequest.ProtoReflect.Descriptor instead.
func (*GetTokenValidityRequest) Descriptor() ([]byte, []int) {
	return file_barpilot_token_renewer_v1_token_proto_rawDescGZIP(), []int{2}
}

func (x *GetTokenValidityRequest) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *GetTokenValidityRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// GetTokenValidityResponse is the response message for the GetTokenValidity RPC.
type GetTokenValidityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expiration    *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=expiration,proto3" json:"expiration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTokenValidityResponse) Reset() {
	*x = GetTokenValidityResponse{}
	mi := &file_barpilot_token_renewer_v1_token_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokenValidityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenValidityResponse) ProtoMessage() {}

func (x *GetTokenValidityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_barpilot_token_renewer_v1_token_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenValidityResponse.ProtoReflect.Descriptor instead.
func (*GetTokenValidityResponse) Descriptor() ([]byte, []int) {
	return file_barpilot_token_renewer_v1_token_proto_rawDescGZIP(), []int{3}
}

func (x *GetTokenValidityResponse) GetExpiration() *timestamppb.Timestamp {
	if x != nil {
		return x.Expiration
	}
	return nil
}

var File_barpilot_token_renewer_v1_token_proto protoreflect.FileDescriptor

const file_barpilot_token_renewer_v1_token_proto_rawDesc = "" +
	"\n" +
	"%barpilot/token_renewer/v1/token.proto\x12\x19barpilot.token_renewer.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1fpluginframework/v1/stream.proto\"E\n" +
	"\x11RenewTokenRequest\x12\x1a\n" +
	"\bmetadata\x18\x01 \x01(\tR\bmetadata\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"\x89\x01\n" +
	"\x12RenewTokenResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12!\n" +
	"\fnew_metadata\x18\x02 \x01(\tR\vnewMetadata\x12:\n" +
	"\n" +
	"expiration\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"expiration\"K\n" +
	"\x17GetTokenValidityRequest\x12\x1a\n" +
	"\bmetadata\x18\x01 \x01(\tR\bmetadata\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"V\n" +
	"\x18GetTokenValidityResponse\x12:\n" +
	"\n" +
	"expiration\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"expiration2\xe4\x02\n" +
	"\x14TokenProviderService\x12i\n" +
	"\n" +
	"RenewToken\x12,.barpilot.token_renewer.v1.RenewTokenRequest\x1a-.barpilot.token_renewer.v1.RenewTokenResponse\x12{\n" +
	"\x10GetTokenValidity\x122.barpilot.token_renewer.v1.GetTokenValidityRequest\x1a3.barpilot.token_renewer.v1.GetTokenValidityResponse\x12d\n" +
	"\fPluginStream\x12'.pluginframework.v1.PluginStreamMessage\x1a'.pluginframework.v1.PluginStreamMessage(\x010\x01B\n" +
	"Z\b./sharedb\x06proto3"

var (
	file_barpilot_token_renewer_v1_token_proto_rawDescOnce sync.Once
	file_barpilot_token_renewer_v1_token_proto_rawDescData []byte
)

func file_barpilot_token_renewer_v1_token_proto_rawDescGZIP() []byte {
	file_barpilot_token_renewer_v1_token_proto_rawDescOnce.Do(func() {
		file_barpilot_token_renewer_v1_token_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_barpilot_token_renewer_v1_token_proto_rawDesc), len(file_barpilot_token_renewer_v1_token_proto_rawDesc)))
	})
	return file_barpilot_token_renewer_v1_token_proto_rawDescData
}

var file_barpilot_token_renewer_v1_token_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_barpilot_token_renewer_v1_token_proto_goTypes = []any{
	(*RenewTokenRequest)(nil),        // 0: barpilot.token_renewer.v1.RenewTokenRequest
	(*RenewTokenResponse)(nil),       // 1: barpilot.token_renewer.v1.RenewTokenResponse
	(*GetTokenValidityRequest)(nil),  // 2: barpilot.token_renewer.v1.GetTokenValidityRequest
	(*GetTokenValidityResponse)(nil), // 3: barpilot.token_renewer.v1.GetTokenValidityResponse
	(*timestamppb.Timestamp)(nil),    // 4: google.protobuf.Timestamp
	(*v1.PluginStreamMessage)(nil),   // 5: pluginframework.v1.PluginStreamMessage
}
var file_barpilot_token_renewer_v1_token_proto_depIdxs = []int32{
	4, // 0: barpilot.token_renewer.v1.RenewTokenResponse.expiration:type_name -> google.protobuf.Timestamp
	4, // 1: barpilot.token_renewer.v1.GetTokenValidityResponse.expiration:type_name -> google.protobuf.Timestamp
	0, // 2: barpilot.token_renewer.v1.TokenProviderService.RenewToken:input_type -> barpilot.token_renewer.v1.RenewTokenRequest
	2, // 3: barpilot.token_renewer.v1.TokenProviderService.GetTokenValidity:input_type -> barpilot.token_renewer.v1.GetTokenValidityRequest
	5, // 4: barpilot.token_renewer.v1.TokenProviderService.PluginStream:input_type -> pluginframework.v1.PluginStreamMessage
	1, // 5: barpilot.token_renewer.v1.TokenProviderService.RenewToken:output_type -> barpilot.token_renewer.v1.RenewTokenResponse
	3, // 6: barpilot.token_renewer.v1.TokenProviderService.GetTokenValidity:output_type -> barpilot.token_renewer.v1.GetTokenValidityResponse
	5, // 7: barpilot.token_renewer.v1.TokenProviderService.PluginStream:output_type -> pluginframework.v1.PluginStreamMessage
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_barpilot_token_renewer_v1_token_proto_init() }
func file_barpilot_token_renewer_v1_token_proto_init() {
	if File_barpilot_token_renewer_v1_token_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_barpilot_token_renewer_v1_token_proto_rawDesc), len(file_barpilot_token_renewer_v1_token_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_barpilot_token_renewer_v1_token_proto_goTypes,
		DependencyIndexes: file_barpilot_token_renewer_v1_token_proto_depIdxs,
		MessageInfos:      file_barpilot_token_renewer_v1_token_proto_msgTypes,
	}.Build()
	File_barpilot_token_renewer_v1_token_proto = out.File
	file_barpilot_token_renewer_v1_token_proto_goTypes = nil
	file_barpilot_token_renewer_v1_token_proto_depIdxs = nil
}
